/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'
import { Route as ApiPublicSubscribeConfirmRouteImport } from './routes/api/public/subscribe.confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeConfirmRoute =
  ApiPublicSubscribeConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiPublicSubscribeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRouteWithChildren
  '/api/public/subscribe/confirm': typeof ApiPublicSubscribeConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRouteWithChildren
  '/api/public/subscribe/confirm': typeof ApiPublicSubscribeConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRouteWithChildren
  '/api/public/subscribe/confirm': typeof ApiPublicSubscribeConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/subscribe' | '/api/public/subscribe/confirm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/subscribe' | '/api/public/subscribe/confirm'
  id:
    | '__root__'
    | '/'
    | '/api/public/subscribe'
    | '/api/public/subscribe/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe/confirm': {
      id: '/api/public/subscribe/confirm'
      path: '/confirm'
      fullPath: '/api/public/subscribe/confirm'
      preLoaderRoute: typeof ApiPublicSubscribeConfirmRouteImport
      parentRoute: typeof ApiPublicSubscribeRoute
    }
  }
}

interface ApiPublicSubscribeRouteChildren {
  ApiPublicSubscribeConfirmRoute: typeof ApiPublicSubscribeConfirmRoute
}

const ApiPublicSubscribeRouteChildren: ApiPublicSubscribeRouteChildren = {
  ApiPublicSubscribeConfirmRoute: ApiPublicSubscribeConfirmRoute,
}

const ApiPublicSubscribeRouteWithChildren =
  ApiPublicSubscribeRoute._addFileChildren(ApiPublicSubscribeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
